# Все доступные смайлики на сервере
# Формат: emoji_id: "символ"
emojis:
  Wolcome: "🔶"
  BetaTester: "🔷"
  Admin: "🔺"
# Смайлик по умолчанию (если игрок не выбрал)
# Если пусто - префикса не будет
default-emoji: ""

# Показывать ли смайлик в tab-листе
tablist-enabled: true

# Показывать ли смайлик над головой (в натеймтеге через Scoreboard Team)
nametag-enabled: true
